import Heights.ForMathlib
import Mathlib

/-!
# The ring of `S`-integers is a Dedekind domain

Let `R` be a Dedekind domain with fraction field `K` and let `S` be a set of primes of `R`.
`Mathlib.RingTheory.DedekindDomain.SInteger` defines the subalgebra `Set.integer S K` of
`S`-integers, `𝒪_S = {x : K | ∀ v ∉ S, v x ≤ 1} = ⋂_{v ∉ S} R_v`, but proves nothing about its
ring structure. This file develops it. The goal is:

* `𝒪_S` is a Dedekind domain with fraction field `K`;
* its height one primes are exactly the `v ∉ S`, via `v ↦ 𝒪_S ∩ v`;
* its class group is `Cl(R)` modulo the subgroup generated by the classes of the `v ∈ S`.

These are the facts needed in `Heights.SelmerGroup` to construct the right-hand map of the
fundamental exact sequence, and they reduce the whole exact sequence to the case `S = ∅`, where
the map to the class group is simply `x ↦ [𝔞]` for the ideal with `𝔞 ^ n = (x)`. They are of
independent interest, and Mathlib has none of them.

## A warning

`𝒪_S` is **not** in general a localization of `R`. Localizing at
`M = {r : R | r ≠ 0 ∧ ∀ v ∉ S, v r = 1}` gives a subring of `𝒪_S`, but it can be strictly
smaller: if `Cl(R) ≅ ℤ` is generated by the class of a single prime `v` and `S = {v}`, then
`M = Rˣ`, because no power `v ^ k` with `k ≠ 0` is principal; yet `𝒪_S ⊋ R`, since for any
integral ideal `𝔞` in the class of `v` the fractional ideal `𝔞 * v⁻¹` is principal, generated by
some `x` with `v x < 1` and `w x ≤ 1` for `w ≠ v`. So `𝒪_S` has to be handled as a general
overring of `R`, not as a ring of fractions. (Every overring of a Dedekind domain is Dedekind,
which is what is proved below in the special case at hand.)

## Implementation notes

`Set.integer S K` is a `Subalgebra R K`. Since it sits between `R` and `K`, the instance
`Localization.subalgebra.instIsFractionRingSubtypeMemSubalgebra` already makes `K` its fraction
field, so `HeightOneSpectrum`-style valuation theory applies as soon as we know it is a Dedekind
domain.

## Main statements

* `IsDedekindDomain.SInteger.isIntegrallyClosed`: `𝒪_S` is integrally closed.
* `IsDedekindDomain.SInteger.isDedekindDomain`: `𝒪_S` is a Dedekind domain.
* `IsDedekindDomain.SInteger.heightOneSpectrumEquiv`: the primes of `𝒪_S` are the `v ∉ S`.
* `IsDedekindDomain.SInteger.classGroupEquiv`: `Cl(𝒪_S) ≃* Cl(R) ⧸ ⟨[v] : v ∈ S⟩`.

## TODO

Everything below `isIntegrallyClosed` is stated but not proved. The intended route:

1. For `v ∉ S`, the localization of `𝒪_S` at the prime `𝔭 v = 𝒪_S ∩ v` is `R_v`, the DVR of `v`
   (`localization_eq_adicCompletionIntegers`-style statement; both are the set of `x : K` with
   `v x ≤ 1`, as every `w ≠ v` can be avoided).
2. Hence `𝒪_S` is a Noetherian domain of Krull dimension at most one whose localizations at
   nonzero primes are DVRs. Mathlib's `IsDedekindDomainDvr` packages the last two conditions;
   `IsDedekindDomainDvr.isDedekindDomain` then gives `IsDedekindDomain 𝒪_S`. Noetherianity is
   the substantial point: every nonzero ideal of `𝒪_S` is `𝔞 * 𝒪_S` for an ideal `𝔞` of `R`.
3. `Ideal.map (algebraMap R 𝒪_S)` induces a surjection on the ideal groups with kernel the
   subgroup generated by the `v ∈ S`, giving `heightOneSpectrumEquiv` and `classGroupEquiv`.
-/

open IsDedekindDomain

namespace IsDedekindDomain.SInteger

variable {R : Type*} [CommRing R] [IsDedekindDomain R] (K : Type*) [Field K] [Algebra R K]
  [IsFractionRing R K] (S : Set (HeightOneSpectrum R))

/-- Membership in the ring of `S`-integers is by definition integrality at all primes off `S`. -/
lemma mem_integer_iff {x : K} : x ∈ S.integer K ↔ ∀ v ∉ S, v.valuation K x ≤ 1 := Iff.rfl

/-- The ring of `S`-integers is contained in the valuation subring of every prime off `S`. -/
lemma toSubring_le_valuationSubring {v : HeightOneSpectrum R} (hv : v ∉ S) :
    (S.integer K).toSubring ≤ (v.valuation K).valuationSubring.toSubring :=
  fun _ hx ↦ hx v hv

/-- The fraction field of the ring of `S`-integers is `K`. This is already an instance, as
`Set.integer S K` is a subalgebra of `K` over `R`. -/
example : IsFractionRing (S.integer K) K := inferInstance

/-- The ring of `S`-integers is integrally closed: it is an intersection of valuation subrings
of `K`, each of which is integrally closed in `K`. -/
instance isIntegrallyClosed : IsIntegrallyClosed (S.integer K) := by
  rw [isIntegrallyClosed_iff K]
  intro x hx
  refine ⟨⟨x, fun v hv ↦ ?_⟩, rfl⟩
  -- work inside the valuation subring `V` of `v`, which contains `𝒪_S`
  set V := (v.valuation K).valuationSubring with hV
  let _ : Algebra (S.integer K) V :=
    (Subring.inclusion (toSubring_le_valuationSubring K S hv)).toAlgebra
  have _ : IsScalarTower (S.integer K) V K := .of_algebraMap_eq fun _ ↦ rfl
  obtain ⟨y, hy⟩ := (isIntegrallyClosed_iff K).mp inferInstance (hx.tower_top (A := V))
  rw [← hy]
  exact y.property

/-!
### The Dedekind property

The remaining statements. `𝒪_S` is Noetherian of dimension at most one with DVR localizations.
-/

instance isNoetherianRing : IsNoetherianRing (S.integer K) :=
  sorry

instance dimensionLEOne : Ring.DimensionLEOne (S.integer K) :=
  sorry

instance isDedekindDomain : IsDedekindDomain (S.integer K) where

/-!
### The height one spectrum

The primes of `𝒪_S` are the primes `v ∉ S`, via `v ↦ 𝒪_S ∩ v`. Under this correspondence the
`v`-adic valuation of `𝒪_S` is the restriction of the `v`-adic valuation of `R`, so the Selmer
group of `𝒪_S` relative to `∅` is the Selmer group of `R` relative to `S`.
-/

/-- The prime of `𝒪_S` below a prime `v ∉ S` of `R`. -/
noncomputable def primeOfNotMem {v : HeightOneSpectrum R} (_ : v ∉ S) :
    HeightOneSpectrum (S.integer K) :=
  sorry

/-- The primes of `𝒪_S` are exactly the primes of `R` not in `S`. -/
noncomputable def heightOneSpectrumEquiv :
    {v : HeightOneSpectrum R // v ∉ S} ≃ HeightOneSpectrum (S.integer K) :=
  sorry

/-- The valuation of `𝒪_S` at the prime below `v` is the valuation of `R` at `v`. -/
lemma valuation_heightOneSpectrumEquiv (v : {v : HeightOneSpectrum R // v ∉ S}) (x : K) :
    (heightOneSpectrumEquiv K S v).valuation K x = (v : HeightOneSpectrum R).valuation K x :=
  sorry

/-!
### The class group
-/

/-- The class group of `𝒪_S` is the class group of `R` modulo the classes of the primes in `S`.

The map `Ideal.map (algebraMap R (S.integer K))` is surjective on nonzero ideals and kills
exactly the primes in `S`. -/
noncomputable def classGroupEquiv :
    ClassGroup (S.integer K) ≃*
      ClassGroup R ⧸ Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) :=
  sorry

end IsDedekindDomain.SInteger
