import Heights.ForMathlib
import Mathlib

/-!
# The ring of `S`-integers is a Dedekind domain

Let `R` be a Dedekind domain with fraction field `K` and let `S` be a set of primes of `R`.
`Mathlib.RingTheory.DedekindDomain.SInteger` defines the subalgebra `Set.integer S K` of
`S`-integers, `𝒪_S = {x : K | ∀ v ∉ S, v x ≤ 1} = ⋂_{v ∉ S} R_v`, but proves nothing about its
ring structure. This file develops it. The goal is:

* `𝒪_S` is a Dedekind domain with fraction field `K`;
* its height one primes are exactly the `v ∉ S`, via `v ↦ 𝒪_S ∩ v`;
* its class group is `Cl(R)` modulo the subgroup generated by the classes of the `v ∈ S`.

These are the facts needed in `Heights.SelmerGroup` to construct the right-hand map of the
fundamental exact sequence, and they reduce the whole exact sequence to the case `S = ∅`, where
the map to the class group is simply `x ↦ [𝔞]` for the ideal with `𝔞 ^ n = (x)`. They are of
independent interest, and Mathlib has none of them.

## A warning

`𝒪_S` is **not** in general a localization of `R`. Localizing at
`M = {r : R | r ≠ 0 ∧ ∀ v ∉ S, v r = 1}` gives a subring of `𝒪_S`, but it can be strictly
smaller: if `Cl(R) ≅ ℤ` is generated by the class of a single prime `v` and `S = {v}`, then
`M = Rˣ`, because no power `v ^ k` with `k ≠ 0` is principal; yet `𝒪_S ⊋ R`, since for any
integral ideal `𝔞` in the class of `v` the fractional ideal `𝔞 * v⁻¹` is principal, generated by
some `x` with `v x < 1` and `w x ≤ 1` for `w ≠ v`. So `𝒪_S` has to be handled as a general
overring of `R`, not as a ring of fractions. (Every overring of a Dedekind domain is Dedekind,
which is what is proved below in the special case at hand.)

## Implementation notes

`Set.integer S K` is a `Subalgebra R K`. Since it sits between `R` and `K`, the instance
`Localization.subalgebra.instIsFractionRingSubtypeMemSubalgebra` already makes `K` its fraction
field, so `HeightOneSpectrum`-style valuation theory applies as soon as we know it is a Dedekind
domain.

## Main statements

* `IsDedekindDomain.SInteger.isIntegrallyClosed`: `𝒪_S` is integrally closed.
* `IsDedekindDomain.SInteger.isDedekindDomain`: `𝒪_S` is a Dedekind domain.
* `IsDedekindDomain.SInteger.heightOneSpectrumEquiv`: the primes of `𝒪_S` are the `v ∉ S`.
* `IsDedekindDomain.SInteger.classGroupEquiv`: `Cl(𝒪_S) ≃* Cl(R) ⧸ ⟨[v] : v ∈ S⟩`.

## TODO

The route, now that `map_asIdeal_eq_top` is available:

1. `denomIdeal_not_le` and `map_denomIdeal_eq_top`: the denominator ideal of an `S`-integer is
   divisible only by primes of `S`, so it extends to the unit ideal. The second reduces to the
   first by factoring the denominator ideal into height one primes (`Ideal.dvd_iff_le`) and
   applying `map_asIdeal_eq_top` to each.
2. `map_comap_eq`: every ideal of `𝒪_S` is extended from `R`. This gives `isNoetherianRing`
   (already proved from it).
3. `dimensionLEOne`, whence `isDedekindDomain`.
4. `heightOneSpectrumEquiv`: `Ideal.map` and `Ideal.comap` are mutually inverse between the
   primes of `R` off `S` and the primes of `𝒪_S`, by 2 and `map_asIdeal_eq_top`.
5. `classGroupEquiv`: `Ideal.map` induces a surjection on the ideal groups whose kernel is the
   subgroup generated by the `v ∈ S`.

-/

open IsDedekindDomain

open scoped nonZeroDivisors

namespace IsDedekindDomain.SInteger

variable {R : Type*} [CommRing R] [IsDedekindDomain R] (K : Type*) [Field K] [Algebra R K]
  [IsFractionRing R K] (S : Set (HeightOneSpectrum R))

/-- Membership in the ring of `S`-integers is by definition integrality at all primes off `S`. -/
lemma mem_integer_iff {x : K} : x ∈ S.integer K ↔ ∀ v ∉ S, v.valuation K x ≤ 1 := Iff.rfl

/-- The ring of `S`-integers is contained in the valuation subring of every prime off `S`. -/
lemma toSubring_le_valuationSubring {v : HeightOneSpectrum R} (hv : v ∉ S) :
    (S.integer K).toSubring ≤ (v.valuation K).valuationSubring.toSubring :=
  fun _ hx ↦ hx v hv

/-- The fraction field of the ring of `S`-integers is `K`. This is already an instance, as
`Set.integer S K` is a subalgebra of `K` over `R`. -/
example : IsFractionRing (S.integer K) K := inferInstance

/-- The ring of `S`-integers is integrally closed: it is an intersection of valuation subrings
of `K`, each of which is integrally closed in `K`. -/
instance isIntegrallyClosed : IsIntegrallyClosed (S.integer K) := by
  rw [isIntegrallyClosed_iff K]
  intro x hx
  refine ⟨⟨x, fun v hv ↦ ?_⟩, rfl⟩
  -- work inside the valuation subring `V` of `v`, which contains `𝒪_S`
  set V := (v.valuation K).valuationSubring with hV
  let _ : Algebra (S.integer K) V :=
    (Subring.inclusion (toSubring_le_valuationSubring K S hv)).toAlgebra
  have _ : IsScalarTower (S.integer K) V K := .of_algebraMap_eq fun _ ↦ rfl
  obtain ⟨y, hy⟩ := (isIntegrallyClosed_iff K).mp inferInstance (hx.tower_top (A := V))
  rw [← hy]
  exact y.property

/-!
### Primes in `S` become the unit ideal

For `v ∈ S` the inverse `v⁻¹` of `v` as a fractional ideal consists of `S`-integers, because an
element `y` with `y * v ⊆ R` can have a pole only at `v`. As `v * v⁻¹ = 1`, the extension of `v`
to `𝒪_S` is therefore the unit ideal. This is the one place where the Dedekind property of `R`
enters, and it is what makes `𝒪_S` bigger than `R`.
-/

/-- A height one prime is not contained in any other one. -/
lemma exists_mem_notMem {v w : HeightOneSpectrum R} (h : w ≠ v) :
    ∃ a ∈ v.asIdeal, a ∉ w.asIdeal := by
  by_contra! hc
  exact h (HeightOneSpectrum.ext (v.isMaximal.eq_of_le w.isPrime.ne_top hc).symm)

/-- For `v ∈ S`, the fractional ideal `v⁻¹` consists of `S`-integers. -/
lemma mem_integer_of_mem_inv {v : HeightOneSpectrum R} (hv : v ∈ S) {y : K}
    (hy : y ∈ (v.asIdeal : FractionalIdeal R⁰ K)⁻¹) : y ∈ S.integer K := by
  intro w hw
  obtain ⟨a, ha, haw⟩ := exists_mem_notMem (show w ≠ v by rintro rfl; exact hw hv)
  have h1 : y * algebraMap R K a ∈ (1 : FractionalIdeal R⁰ K) :=
    (FractionalIdeal.mem_inv_iff (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot)).mp hy _
      (FractionalIdeal.mem_coeIdeal_of_mem R⁰ ha)
  obtain ⟨r, hr⟩ := (FractionalIdeal.mem_one_iff _).mp h1
  have h2 : w.valuation K (y * algebraMap R K a) ≤ 1 := hr ▸ w.valuation_le_one r
  rwa [map_mul, w.valuation_eq_one_iff_notMem.mpr haw, mul_one] at h2

/-- For `v ∈ S`, the extension of `v` to the ring of `S`-integers is the unit ideal. -/
lemma map_asIdeal_eq_top {v : HeightOneSpectrum R} (hv : v ∈ S) :
    Ideal.map (algebraMap R (S.integer K)) v.asIdeal = ⊤ := by
  set A := S.integer K with hA
  set M := Ideal.map (algebraMap R A) v.asIdeal with hM
  -- `1 ∈ v * v⁻¹`, as a submodule of `K`
  have h1 : (1 : K) ∈
      (v.asIdeal : FractionalIdeal R⁰ K) * (v.asIdeal : FractionalIdeal R⁰ K)⁻¹ := by
    rw [FractionalIdeal.coe_ideal_mul_inv _ v.ne_bot]
    exact (FractionalIdeal.mem_one_iff _).mpr ⟨1, map_one _⟩
  rw [← FractionalIdeal.mem_coe, FractionalIdeal.coe_mul] at h1
  -- every element of the product that is an `S`-integer lies in `M`
  refine Ideal.eq_top_iff_one M |>.mpr ?_
  suffices H : ∀ x ∈ (v.asIdeal : FractionalIdeal R⁰ K) * (v.asIdeal : FractionalIdeal R⁰ K)⁻¹,
      ∃ hx : x ∈ A, (⟨x, hx⟩ : A) ∈ M by
    obtain ⟨hx, hx'⟩ := H 1 (by rwa [← FractionalIdeal.coe_mul, FractionalIdeal.mem_coe] at h1)
    exact (show (⟨1, hx⟩ : A) = 1 from rfl) ▸ hx'
  intro x hx
  rw [← FractionalIdeal.mem_coe, FractionalIdeal.coe_mul] at hx
  refine Submodule.mul_induction_on hx (fun a ha y hy ↦ ?_) (fun x y hx hy ↦ ?_)
  · obtain ⟨a, ha', rfl⟩ := (FractionalIdeal.mem_coeIdeal R⁰).mp
      ((FractionalIdeal.mem_coe (I := (v.asIdeal : FractionalIdeal R⁰ K))).mpr ha)
    have hyA : y ∈ A := mem_integer_of_mem_inv K S hv
      ((FractionalIdeal.mem_coe (I := (v.asIdeal : FractionalIdeal R⁰ K)⁻¹)).mpr hy)
    have haA : algebraMap R K a ∈ A := A.algebraMap_mem a
    refine ⟨mul_mem haA hyA, ?_⟩
    have he : (⟨algebraMap R K a * y, mul_mem haA hyA⟩ : A) = algebraMap R A a * ⟨y, hyA⟩ := rfl
    rw [he]
    exact Ideal.mul_mem_right _ M (Ideal.mem_map_of_mem _ ha')
  · obtain ⟨hx, hx'⟩ := hx
    obtain ⟨hy, hy'⟩ := hy
    exact ⟨add_mem hx hy, add_mem hx' hy'⟩

/-!
### Ideals of `𝒪_S` are extended from `R`

Let `I` be an ideal of `𝒪_S` and `J = I ∩ R` its contraction. For `x ∈ I` the denominator ideal
`𝔡 x = {r : R | r * x ∈ R}` is divisible only by primes in `S`, because `x` is `w`-integral for
`w ∉ S`. Hence `𝔡 x * 𝒪_S = ⊤` by `map_asIdeal_eq_top`, so `1 = ∑ dᵢ cᵢ` with `dᵢ ∈ 𝔡 x` and
`cᵢ ∈ 𝒪_S`, and `x = ∑ (dᵢ * x) * cᵢ` exhibits `x` as an element of `J * 𝒪_S`, since
`dᵢ * x ∈ R ∩ I = J`.

Noetherianity is immediate from this: `J` is finitely generated as `R` is Noetherian, hence so
is its extension `I`.
-/

/-- The denominator ideal of `x : K`: the `r : R` with `r * x ∈ R`. -/
def denomIdeal (x : K) : Ideal R where
  carrier := {r : R | ∃ s : R, algebraMap R K r * x = algebraMap R K s}
  zero_mem' := ⟨0, by simp⟩
  add_mem' := by
    rintro a b ⟨s, hs⟩ ⟨t, ht⟩
    exact ⟨s + t, by rw [map_add, add_mul, hs, ht, map_add]⟩
  smul_mem' := by
    rintro c a ⟨s, hs⟩
    exact ⟨c * s, by rw [smul_eq_mul, map_mul, mul_assoc, hs, map_mul]⟩

lemma mem_denomIdeal_iff {x : K} {r : R} :
    r ∈ denomIdeal K x ↔ ∃ s : R, algebraMap R K r * x = algebraMap R K s :=
  Iff.rfl

/-- The denominator ideal of an `S`-integer is not contained in any prime off `S`: at such a
prime `x` is integral, so it has a denominator away from the prime. -/
lemma denomIdeal_not_le {x : K} (hx : x ∈ S.integer K) {w : HeightOneSpectrum R} (hw : w ∉ S) :
    ¬ denomIdeal K x ≤ w.asIdeal :=
  sorry

/-- The denominator ideal of an `S`-integer extends to the unit ideal of `𝒪_S`: all its prime
factors lie in `S`, and each of those extends to the unit ideal by `map_asIdeal_eq_top`. -/
lemma map_denomIdeal_eq_top {x : K} (hx : x ∈ S.integer K) :
    Ideal.map (algebraMap R (S.integer K)) (denomIdeal K x) = ⊤ :=
  sorry

/-- **Every ideal of `𝒪_S` is extended from `R`.** -/
theorem map_comap_eq (I : Ideal (S.integer K)) :
    Ideal.map (algebraMap R (S.integer K)) (I.comap (algebraMap R (S.integer K))) = I :=
  sorry

/-!
### The Dedekind property
-/

instance isNoetherianRing : IsNoetherianRing (S.integer K) := by
  refine (isNoetherianRing_iff_ideal_fg _).mpr fun I ↦ ?_
  rw [← map_comap_eq K S I]
  exact Ideal.FG.map (IsNoetherian.noetherian (R := R) (I.comap (algebraMap R (S.integer K))))
    (algebraMap R (S.integer K))

instance dimensionLEOne : Ring.DimensionLEOne (S.integer K) :=
  sorry

instance isDedekindDomain : IsDedekindDomain (S.integer K) where

/-!
### The height one spectrum

The primes of `𝒪_S` are the primes `v ∉ S`, via `v ↦ 𝒪_S ∩ v`. Under this correspondence the
`v`-adic valuation of `𝒪_S` is the restriction of the `v`-adic valuation of `R`, so the Selmer
group of `𝒪_S` relative to `∅` is the Selmer group of `R` relative to `S`.
-/

/-- The prime of `𝒪_S` below a prime `v ∉ S` of `R`. -/
noncomputable def primeOfNotMem {v : HeightOneSpectrum R} (_ : v ∉ S) :
    HeightOneSpectrum (S.integer K) :=
  sorry

/-- The primes of `𝒪_S` are exactly the primes of `R` not in `S`. -/
noncomputable def heightOneSpectrumEquiv :
    {v : HeightOneSpectrum R // v ∉ S} ≃ HeightOneSpectrum (S.integer K) :=
  sorry

/-- The valuation of `𝒪_S` at the prime below `v` is the valuation of `R` at `v`. -/
lemma valuation_heightOneSpectrumEquiv (v : {v : HeightOneSpectrum R // v ∉ S}) (x : K) :
    (heightOneSpectrumEquiv K S v).valuation K x = (v : HeightOneSpectrum R).valuation K x :=
  sorry

/-!
### The class group
-/

/-- The class group of `𝒪_S` is the class group of `R` modulo the classes of the primes in `S`.

The map `Ideal.map (algebraMap R (S.integer K))` is surjective on nonzero ideals and kills
exactly the primes in `S`. -/
noncomputable def classGroupEquiv :
    ClassGroup (S.integer K) ≃*
      ClassGroup R ⧸ Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) :=
  sorry

end IsDedekindDomain.SInteger
