import Heights.ForMathlib.Basic
import Heights.ForMathlib.FractionalIdeal
import Mathlib

/-!
# The ring of `S`-integers is a Dedekind domain

Let `R` be a Dedekind domain with fraction field `K` and let `S` be a set of primes of `R`.
`Mathlib.RingTheory.DedekindDomain.SInteger` defines the subalgebra `Set.integer S K` of
`S`-integers, `𝒪_S = {x : K | ∀ v ∉ S, v x ≤ 1} = ⋂_{v ∉ S} R_v`, but proves nothing about its
ring structure. This file develops it. The goal is:

* `𝒪_S` is a Dedekind domain with fraction field `K`;
* its height one primes are exactly the `v ∉ S`, via `v ↦ 𝒪_S ∩ v`;
* its class group is `Cl(R)` modulo the subgroup generated by the classes of the `v ∈ S`.

These are the facts needed in `Heights.ForMathlib.SelmerGroup` to construct the right-hand map of the
fundamental exact sequence, and they reduce the whole exact sequence to the case `S = ∅`, where
the map to the class group is simply `x ↦ [𝔞]` for the ideal with `𝔞 ^ n = (x)`. They are of
independent interest, and Mathlib has none of them.

## A warning

`𝒪_S` is **not** in general a localization of `R`. Localizing at
`M = {r : R | r ≠ 0 ∧ ∀ v ∉ S, v r = 1}` gives a subring of `𝒪_S`, but it can be strictly
smaller: if `Cl(R) ≅ ℤ` is generated by the class of a single prime `v` and `S = {v}`, then
`M = Rˣ`, because no power `v ^ k` with `k ≠ 0` is principal; yet `𝒪_S ⊋ R`, since for any
integral ideal `𝔞` in the class of `v` the fractional ideal `𝔞 * v⁻¹` is principal, generated by
some `x` with `v x < 1` and `w x ≤ 1` for `w ≠ v`. So `𝒪_S` has to be handled as a general
overring of `R`, not as a ring of fractions.

The classical statement in the appropriate generality is that *every* overring of a Dedekind
domain (i.e. every ring between `R` and `K`) is a Dedekind domain. The proofs below use the
`S`-integer description directly (via the denominator-ideal argument in `map_comap_eq`), which
keeps them short; upstreaming to Mathlib might instead aim for the general overring statement.

## Implementation notes

`Set.integer S K` is a `Subalgebra R K`. Since it sits between `R` and `K`, the instance
`Localization.subalgebra.instIsFractionRingSubtypeMemSubalgebra` already makes `K` its fraction
field, so `HeightOneSpectrum`-style valuation theory applies as soon as we know it is a Dedekind
domain.

## Main statements

* `IsDedekindDomain.SInteger.isIntegrallyClosed`: `𝒪_S` is integrally closed.
* `IsDedekindDomain.SInteger.isDedekindDomain`: `𝒪_S` is a Dedekind domain.
* `IsDedekindDomain.SInteger.heightOneSpectrumEquiv`: the primes of `𝒪_S` are the `v ∉ S`, and
  `valuation_heightOneSpectrumEquiv`: the valuations restrict those of `R`.
* `IsDedekindDomain.SInteger.extendedHom_surjective` and `finite_classGroup`: extension of ideals
  `Cl(R) → Cl(𝒪_S)` is surjective, so `Cl(𝒪_S)` is finite whenever `Cl(R)` is.
* `IsDedekindDomain.SInteger.classGroupEquiv`: `Cl(𝒪_S) ≃* Cl(R) ⧸ ⟨[v] : v ∈ S⟩`.

-/

open IsDedekindDomain FractionalIdeal

open scoped nonZeroDivisors Classical

section DenomIdeal

variable {R : Type*} [CommRing R] (K : Type*) [CommRing K] [Algebra R K]

/-- The denominator ideal of `x : K`: the colon ideal `(R : x) = {r : R | r • x ∈ R}`. -/
abbrev IsDedekindDomain.SInteger.denomIdeal (x : K) : Ideal R := (1 : Submodule R K).colon {x}

lemma IsDedekindDomain.SInteger.mem_denomIdeal_iff {x : K} {r : R} :
    r ∈ denomIdeal K x ↔ ∃ s : R, algebraMap R K r * x = algebraMap R K s := by
  rw [Submodule.mem_colon_singleton, Algebra.smul_def, Submodule.mem_one]
  exact exists_congr fun s ↦ eq_comm

end DenomIdeal

namespace IsDedekindDomain.SInteger

variable {R : Type*} [CommRing R] [IsDedekindDomain R] (K : Type*) [Field K] [Algebra R K]
  [IsFractionRing R K] (S : Set (HeightOneSpectrum R))

lemma mem_integer_iff {x : K} : x ∈ S.integer K ↔ ∀ v ∉ S, v.valuation K x ≤ 1 := Iff.rfl

lemma toSubring_le_valuationSubring {v : HeightOneSpectrum R} (hv : v ∉ S) :
    (S.integer K).toSubring ≤ (v.valuation K).valuationSubring.toSubring :=
  fun _ hx ↦ hx v hv

/-- The fraction field of the ring of `S`-integers is `K`. This is already an instance, as
`Set.integer S K` is a subalgebra of `K` over `R`. -/
example : IsFractionRing (S.integer K) K := inferInstance

/-- The ring of `S`-integers is integrally closed: it is an intersection of valuation subrings
of `K`, each of which is integrally closed in `K`. -/
instance isIntegrallyClosed : IsIntegrallyClosed (S.integer K) := by
  rw [isIntegrallyClosed_iff K]
  intro x hx
  refine ⟨⟨x, fun v hv ↦ ?_⟩, rfl⟩
  -- work inside the valuation subring `V` of `v`, which contains `𝒪_S`
  set V := (v.valuation K).valuationSubring with hV
  let _ : Algebra (S.integer K) V :=
    (Subring.inclusion (toSubring_le_valuationSubring K S hv)).toAlgebra
  have _ : IsScalarTower (S.integer K) V K := .of_algebraMap_eq fun _ ↦ rfl
  obtain ⟨y, hy⟩ := (isIntegrallyClosed_iff K).mp inferInstance (hx.tower_top (A := V))
  rw [← hy]
  exact y.property

/-!
### Primes in `S` become the unit ideal

For `v ∈ S` the inverse `v⁻¹` of `v` as a fractional ideal consists of `S`-integers, because an
element `y` with `y * v ⊆ R` can have a pole only at `v`. As `v * v⁻¹ = 1`, the extension of `v`
to `𝒪_S` is therefore the unit ideal. This is the one place where the Dedekind property of `R`
enters, and it is what makes `𝒪_S` bigger than `R`.
-/

/-- A height one prime is not contained in any other one. -/
lemma exists_mem_notMem {v w : HeightOneSpectrum R} (h : w ≠ v) :
    ∃ a ∈ v.asIdeal, a ∉ w.asIdeal := by
  by_contra! hc
  exact h (HeightOneSpectrum.ext (v.isMaximal.eq_of_le w.isPrime.ne_top hc).symm)

/-- For `v ∈ S`, the fractional ideal `v⁻¹` consists of `S`-integers. -/
lemma mem_integer_of_mem_inv {v : HeightOneSpectrum R} (hv : v ∈ S) {y : K}
    (hy : y ∈ (v.asIdeal : FractionalIdeal R⁰ K)⁻¹) : y ∈ S.integer K := by
  intro w hw
  obtain ⟨a, ha, haw⟩ := exists_mem_notMem (show w ≠ v by rintro rfl; exact hw hv)
  have h1 : y * algebraMap R K a ∈ (1 : FractionalIdeal R⁰ K) :=
    (FractionalIdeal.mem_inv_iff (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot)).mp hy _
      (FractionalIdeal.mem_coeIdeal_of_mem R⁰ ha)
  obtain ⟨r, hr⟩ := (FractionalIdeal.mem_one_iff _).mp h1
  have h2 : w.valuation K (y * algebraMap R K a) ≤ 1 := hr ▸ w.valuation_le_one r
  rwa [map_mul, w.valuation_eq_one_iff_notMem.mpr haw, mul_one] at h2

/-- For `v ∈ S`, the extension of `v` to the ring of `S`-integers is the unit ideal. -/
lemma map_asIdeal_eq_top {v : HeightOneSpectrum R} (hv : v ∈ S) :
    Ideal.map (algebraMap R (S.integer K)) v.asIdeal = ⊤ := by
  set A := S.integer K with hA
  set M := Ideal.map (algebraMap R A) v.asIdeal with hM
  -- `1 ∈ v * v⁻¹`, as a submodule of `K`
  have h1 : (1 : K) ∈
      (v.asIdeal : FractionalIdeal R⁰ K) * (v.asIdeal : FractionalIdeal R⁰ K)⁻¹ := by
    rw [FractionalIdeal.coe_ideal_mul_inv _ v.ne_bot]
    exact (FractionalIdeal.mem_one_iff _).mpr ⟨1, map_one _⟩
  rw [← FractionalIdeal.mem_coe, FractionalIdeal.coe_mul] at h1
  -- every element of the product that is an `S`-integer lies in `M`
  refine Ideal.eq_top_iff_one M |>.mpr ?_
  suffices H : ∀ x ∈ (v.asIdeal : FractionalIdeal R⁰ K) * (v.asIdeal : FractionalIdeal R⁰ K)⁻¹,
      ∃ hx : x ∈ A, (⟨x, hx⟩ : A) ∈ M by
    obtain ⟨hx, hx'⟩ := H 1 (by rwa [← FractionalIdeal.coe_mul, FractionalIdeal.mem_coe] at h1)
    exact (show (⟨1, hx⟩ : A) = 1 from rfl) ▸ hx'
  intro x hx
  rw [← FractionalIdeal.mem_coe, FractionalIdeal.coe_mul] at hx
  refine Submodule.mul_induction_on hx (fun a ha y hy ↦ ?_) (fun x y hx hy ↦ ?_)
  · obtain ⟨a, ha', rfl⟩ := (FractionalIdeal.mem_coeIdeal R⁰).mp
      ((FractionalIdeal.mem_coe (I := (v.asIdeal : FractionalIdeal R⁰ K))).mpr ha)
    have hyA : y ∈ A := mem_integer_of_mem_inv K S hv
      ((FractionalIdeal.mem_coe (I := (v.asIdeal : FractionalIdeal R⁰ K)⁻¹)).mpr hy)
    have haA : algebraMap R K a ∈ A := A.algebraMap_mem a
    refine ⟨mul_mem haA hyA, ?_⟩
    have he : (⟨algebraMap R K a * y, mul_mem haA hyA⟩ : A) = algebraMap R A a * ⟨y, hyA⟩ := rfl
    rw [he]
    exact Ideal.mul_mem_right _ M (Ideal.mem_map_of_mem _ ha')
  · obtain ⟨hx, hx'⟩ := hx
    obtain ⟨hy, hy'⟩ := hy
    exact ⟨add_mem hx hy, add_mem hx' hy'⟩

/-!
### Ideals of `𝒪_S` are extended from `R`

Let `I` be an ideal of `𝒪_S` and `J = I ∩ R` its contraction. For `x ∈ I` the denominator ideal
`𝔡 x = {r : R | r * x ∈ R}` is divisible only by primes in `S`, because `x` is `w`-integral for
`w ∉ S`. Hence `𝔡 x * 𝒪_S = ⊤` by `map_asIdeal_eq_top`, so `1 = ∑ dᵢ cᵢ` with `dᵢ ∈ 𝔡 x` and
`cᵢ ∈ 𝒪_S`, and `x = ∑ (dᵢ * x) * cᵢ` exhibits `x` as an element of `J * 𝒪_S`, since
`dᵢ * x ∈ R ∩ I = J`.

Noetherianity is immediate from this: `J` is finitely generated as `R` is Noetherian, hence so
is its extension `I`.
-/

/-- The denominator ideal of an `S`-integer is not contained in any prime off `S`: at such a
prime `x` is integral, so it has a denominator away from the prime. -/
lemma denomIdeal_not_le {x : K} (hx : x ∈ S.integer K) {w : HeightOneSpectrum R} (hw : w ∉ S) :
    ¬ denomIdeal K x ≤ w.asIdeal := by
  obtain ⟨n, d, hnd⟩ := HeightOneSpectrum.exists_primeCompl_mul_eq_of_integer w x (hx w hw)
  refine fun hle ↦ d.property (hle ?_)
  rw [mem_denomIdeal_iff]
  exact ⟨n, by rw [mul_comm]; exact hnd⟩

/-- The denominator ideal of any `x : K` is nonzero: a common denominator lies in it. -/
lemma denomIdeal_ne_bot (x : K) : denomIdeal K x ≠ (⊥ : Ideal R) := by
  obtain ⟨⟨a, b, hb⟩, hab⟩ := IsLocalization.surj R⁰ x
  refine fun h0 ↦ nonZeroDivisors.ne_zero hb ?_
  have : b ∈ denomIdeal K x := by rw [mem_denomIdeal_iff]; exact ⟨a, by rw [mul_comm]; exact hab⟩
  simpa [h0] using this

/-- The denominator ideal of an `S`-integer extends to the unit ideal of `𝒪_S`: all its prime
factors lie in `S`, and each of those extends to the unit ideal by `map_asIdeal_eq_top`. -/
lemma map_denomIdeal_eq_top {x : K} (hx : x ∈ S.integer K) :
    Ideal.map (algebraMap R (S.integer K)) (denomIdeal K x) = ⊤ := by
  by_contra h
  obtain ⟨M, hM, hle⟩ := Ideal.exists_le_maximal _ h
  have h𝔭le : denomIdeal K x ≤ M.comap (algebraMap R (S.integer K)) :=
    (Ideal.le_comap_map).trans (Ideal.comap_mono hle)
  have h𝔭ne : M.comap (algebraMap R (S.integer K)) ≠ ⊥ :=
    fun h0 ↦ denomIdeal_ne_bot K x (le_bot_iff.mp (h0 ▸ h𝔭le))
  have hprime : (M.comap (algebraMap R (S.integer K))).IsPrime := hM.isPrime.comap _
  have hwS : (⟨_, hprime, h𝔭ne⟩ : HeightOneSpectrum R) ∈ S :=
    by_contra fun hwn ↦ denomIdeal_not_le K S hx hwn h𝔭le
  have htop := map_asIdeal_eq_top K S hwS
  exact hM.ne_top (top_le_iff.mp (htop.ge.trans Ideal.map_comap_le))

/-- **Every ideal of `𝒪_S` is extended from `R`.** -/
theorem map_comap_eq (I : Ideal (S.integer K)) :
    Ideal.map (algebraMap R (S.integer K)) (I.comap (algebraMap R (S.integer K))) = I := by
  refine le_antisymm Ideal.map_comap_le fun x hx ↦ ?_
  set f := algebraMap R (S.integer K) with hf
  set J' := Ideal.map f (I.comap f) with hJ'
  have coeval (r : R) : ((f r : S.integer K) : K) = algebraMap R K r := by
    rw [IsScalarTower.algebraMap_apply R (S.integer K) K]; rfl
  -- for a denominator `d` of `x`, the product `f d * x` is extended from `R` and lies in `I`
  have key (d : R) (hd : d ∈ denomIdeal K (x : K)) : f d * x ∈ J' := by
    rw [mem_denomIdeal_iff] at hd
    obtain ⟨s, hs⟩ := hd
    have hfx : f d * x = f s := by
      apply Subtype.val_injective
      rw [Subalgebra.coe_mul, coeval d, coeval s, hs]
    rw [hfx]
    exact Ideal.mem_map_of_mem f (show f s ∈ I from hfx ▸ I.mul_mem_left _ hx)
  -- the elements `r` with `r * x ∈ J'` form an ideal containing the extension of `denomIdeal`
  let K' : Ideal (S.integer K) :=
    { carrier := {r | r * x ∈ J'}
      zero_mem' := by simp
      add_mem' := fun {a b} ha hb ↦ by simpa [add_mul] using J'.add_mem ha hb
      smul_mem' := fun c {a} ha ↦ by
        simpa only [smul_eq_mul, Set.mem_setOf_eq, mul_assoc] using J'.mul_mem_left c ha }
  have hsub : Ideal.map f (denomIdeal K (x : K)) ≤ K' := Ideal.map_le_iff_le_comap.mpr key
  have hmtop : Ideal.map f (denomIdeal K (x : K)) = ⊤ := map_denomIdeal_eq_top K S x.property
  have h1 : (1 : S.integer K) * x ∈ J' := hsub (hmtop.ge Submodule.mem_top)
  simpa using h1

/-!
### The Dedekind property
-/

/-- The ring of `S`-integers is Noetherian: every ideal is extended from the Noetherian
ring `R` by `map_comap_eq`. -/
instance isNoetherianRing : IsNoetherianRing (S.integer K) := by
  refine (isNoetherianRing_iff_ideal_fg _).mpr fun I ↦ ?_
  rw [← map_comap_eq K S I]
  exact Ideal.FG.map (IsNoetherian.noetherian (R := R) (I.comap (algebraMap R (S.integer K))))
    (algebraMap R (S.integer K))

/-- The contraction to `R` of a nonzero prime of `𝒪_S` is a nonzero prime: if it were zero, the
prime would be `map ⊥ = ⊥` by `map_comap_eq`. -/
lemma comap_ne_bot {P : Ideal (S.integer K)} (hP : P ≠ ⊥) :
    P.comap (algebraMap R (S.integer K)) ≠ ⊥ := by
  intro h0
  exact hP (by rw [← map_comap_eq K S P, h0, Ideal.map_bot])

/-- The ring of `S`-integers has Krull dimension at most `1`: the contraction to `R` of a
nonzero prime is maximal, and equalities of ideals lift back through `map_comap_eq`. -/
instance dimensionLEOne : Ring.DimensionLEOne (S.integer K) := by
  refine ⟨fun {P} hP hPp ↦ ?_⟩
  set f := algebraMap R (S.integer K) with hf
  -- pass to a maximal ideal `M` above `P` and compare contractions in `R`
  obtain ⟨M, hM, hPM⟩ := P.exists_le_maximal hPp.ne_top
  have hcP : P.comap f ≠ ⊥ := comap_ne_bot K S hP
  have hMne : M ≠ ⊥ := fun h ↦ hP (le_bot_iff.mp (h ▸ hPM))
  have hcM : M.comap f ≠ ⊥ := comap_ne_bot K S hMne
  -- both contractions are maximal in `R`, and one contains the other, so they are equal
  have hcPmax : (P.comap f).IsMaximal :=
    Ring.DimensionLEOne.maximalOfPrime hcP (hPp.comap f)
  have hcMprime : (M.comap f).IsPrime := hM.isPrime.comap f
  have heq : P.comap f = M.comap f :=
    hcPmax.eq_of_le hcMprime.ne_top (Ideal.comap_mono hPM)
  -- lift the equality back through `map_comap_eq`
  rwa [← map_comap_eq K S P, heq, map_comap_eq K S M]

/-- **The ring of `S`-integers of a Dedekind domain is a Dedekind domain.** -/
instance isDedekindDomain : IsDedekindDomain (S.integer K) where

/-!
### The height one spectrum

The primes of `𝒪_S` are the primes `v ∉ S`, via `v ↦ 𝒪_S ∩ v`. Under this correspondence the
`v`-adic valuation of `𝒪_S` is the restriction of the `v`-adic valuation of `R`, so the Selmer
group of `𝒪_S` relative to `∅` is the Selmer group of `R` relative to `S`.
-/

/-- For `v ∉ S`, the extension of `v` to `𝒪_S` is a proper ideal: it is contained in the proper
ideal of `S`-integers with `v`-valuation `< 1` (which does not contain `1`). -/
lemma map_asIdeal_ne_top {v : HeightOneSpectrum R} (hv : v ∉ S) :
    Ideal.map (algebraMap R (S.integer K)) v.asIdeal ≠ ⊤ := by
  set f := algebraMap R (S.integer K) with hf
  have coeval (r : R) : ((f r : S.integer K) : K) = algebraMap R K r := by
    rw [IsScalarTower.algebraMap_apply R (S.integer K) K]; rfl
  let 𝔪 : Ideal (S.integer K) :=
    { carrier := {x | v.valuation K (x : K) < 1}
      zero_mem' := by simp
      add_mem' := fun {a b} ha hb ↦ by
        rw [Set.mem_setOf_eq, Subalgebra.coe_add]
        exact lt_of_le_of_lt ((v.valuation K).map_add _ _) (max_lt ha hb)
      smul_mem' := fun c {a} ha ↦ by
        have hc : v.valuation K (c : K) ≤ 1 := c.property v hv
        rw [Set.mem_setOf_eq, smul_eq_mul, Subalgebra.coe_mul, map_mul]
        calc v.valuation K (c : K) * v.valuation K (a : K)
            ≤ 1 * v.valuation K (a : K) := by gcongr
          _ = v.valuation K (a : K) := one_mul _
          _ < 1 := ha }
  have hle : Ideal.map f v.asIdeal ≤ 𝔪 :=
    Ideal.map_le_iff_le_comap.mpr fun a ha ↦ by
      show v.valuation K ((f a : S.integer K) : K) < 1
      rw [coeval]; exact (v.valuation_lt_one_iff_mem a).mpr ha
  intro htop
  have h1 : v.valuation K ((1 : S.integer K) : K) < 1 := le_trans htop.ge hle Submodule.mem_top
  simp at h1

lemma comap_map_asIdeal {v : HeightOneSpectrum R} (hv : v ∉ S) :
    (Ideal.map (algebraMap R (S.integer K)) v.asIdeal).comap (algebraMap R (S.integer K)) =
      v.asIdeal := by
  set f := algebraMap R (S.integer K) with hf
  refine (v.isMaximal.eq_of_le ?_ Ideal.le_comap_map).symm
  rw [Ne, Ideal.comap_eq_top_iff]
  exact map_asIdeal_ne_top K S hv

lemma isMaximal_map_asIdeal {v : HeightOneSpectrum R} (hv : v ∉ S) :
    (Ideal.map (algebraMap R (S.integer K)) v.asIdeal).IsMaximal := by
  set f := algebraMap R (S.integer K) with hf
  obtain ⟨M, hM, hle⟩ := Ideal.exists_le_maximal _ (map_asIdeal_ne_top K S hv)
  have hcle : v.asIdeal ≤ M.comap f := (comap_map_asIdeal K S hv).ge.trans (Ideal.comap_mono hle)
  have hceq : M.comap f = v.asIdeal :=
    (v.isMaximal.eq_of_le (hM.isPrime.comap f).ne_top hcle).symm
  rwa [← map_comap_eq K S M, hceq] at hM

/-- The extension of `v` to `𝒪_S` is a nonzero ideal: `v` is nonzero and the map is injective. -/
lemma map_asIdeal_ne_bot {v : HeightOneSpectrum R} (hv : v ∉ S) :
    Ideal.map (algebraMap R (S.integer K)) v.asIdeal ≠ ⊥ := by
  intro h
  refine v.ne_bot ?_
  rw [← comap_map_asIdeal K S hv, h,
    Ideal.comap_bot_of_injective _ (FaithfulSMul.algebraMap_injective R (S.integer K))]

/-- The prime of `𝒪_S` above a prime `v ∉ S` of `R`: the extension of `v`. -/
noncomputable def primeOfNotMem {v : HeightOneSpectrum R} (hv : v ∉ S) :
    HeightOneSpectrum (S.integer K) where
  asIdeal := Ideal.map (algebraMap R (S.integer K)) v.asIdeal
  isPrime := (isMaximal_map_asIdeal K S hv).isPrime
  ne_bot := map_asIdeal_ne_bot K S hv

@[simp] lemma primeOfNotMem_asIdeal {v : HeightOneSpectrum R} (hv : v ∉ S) :
    (primeOfNotMem K S hv).asIdeal = Ideal.map (algebraMap R (S.integer K)) v.asIdeal :=
  rfl

/-- The prime of `R` below a prime `P` of `𝒪_S`. -/
noncomputable def primeBelow (P : HeightOneSpectrum (S.integer K)) : HeightOneSpectrum R where
  asIdeal := P.asIdeal.comap (algebraMap R (S.integer K))
  isPrime := P.isPrime.comap _
  ne_bot := comap_ne_bot K S P.ne_bot

@[simp] lemma primeBelow_asIdeal (P : HeightOneSpectrum (S.integer K)) :
    (primeBelow K S P).asIdeal = P.asIdeal.comap (algebraMap R (S.integer K)) :=
  rfl

lemma primeBelow_notMem (P : HeightOneSpectrum (S.integer K)) : primeBelow K S P ∉ S := by
  intro hv
  have h1 := map_asIdeal_eq_top K S hv
  rw [primeBelow_asIdeal, map_comap_eq] at h1
  exact P.isPrime.ne_top h1

/-- The primes of `𝒪_S` are exactly the primes of `R` not in `S`. -/
noncomputable def heightOneSpectrumEquiv :
    {v : HeightOneSpectrum R // v ∉ S} ≃ HeightOneSpectrum (S.integer K) where
  toFun v := primeOfNotMem K S v.property
  invFun P := ⟨primeBelow K S P, primeBelow_notMem K S P⟩
  left_inv v := Subtype.ext <| HeightOneSpectrum.ext <| comap_map_asIdeal K S v.property
  right_inv P := HeightOneSpectrum.ext <| map_comap_eq K S P.asIdeal

@[simp] lemma heightOneSpectrumEquiv_apply (v : {v : HeightOneSpectrum R // v ∉ S}) :
    heightOneSpectrumEquiv K S v = primeOfNotMem K S v.property :=
  rfl

@[simp] lemma heightOneSpectrumEquiv_symm_apply (P : HeightOneSpectrum (S.integer K)) :
    ((heightOneSpectrumEquiv K S).symm P : HeightOneSpectrum R) = primeBelow K S P :=
  rfl

/-- For `v ∉ S`, the contraction of the extension of `v ^ n` is `v ^ n`: the contraction divides
`v ^ n`, so it is `v ^ j`; extending back gives `Pⱼ = Pₙ`, whence `j = n`. -/
lemma comap_map_pow {v : HeightOneSpectrum R} (hv : v ∉ S) (n : ℕ) :
    (Ideal.map (algebraMap R (S.integer K)) (v.asIdeal ^ n)).comap
        (algebraMap R (S.integer K)) = v.asIdeal ^ n := by
  set f := algebraMap R (S.integer K) with hf
  have hP0 : Ideal.map f v.asIdeal ≠ 0 := map_asIdeal_ne_bot K S hv
  have hPnu : ¬ IsUnit (Ideal.map f v.asIdeal) :=
    fun h ↦ map_asIdeal_ne_top K S hv (Ideal.isUnit_iff.mp h)
  refine le_antisymm ?_ Ideal.le_comap_map
  have hdvd : (Ideal.map f (v.asIdeal ^ n)).comap f ∣ v.asIdeal ^ n :=
    Ideal.dvd_iff_le.mpr Ideal.le_comap_map
  obtain ⟨j, -, hassoc⟩ := (dvd_prime_pow v.prime n).mp hdvd
  rw [associated_iff_eq] at hassoc
  have hmapQ : Ideal.map f ((Ideal.map f (v.asIdeal ^ n)).comap f) =
      Ideal.map f (v.asIdeal ^ n) := map_comap_eq K S _
  rw [hassoc, Ideal.map_pow, Ideal.map_pow] at hmapQ
  rw [hassoc, (pow_inj_of_not_isUnit hPnu hP0).mp hmapQ]

/-- For `v ∉ S`, the `Pᵥ`-adic valuation on `R` (computed in `𝒪_S`) is the `v`-adic valuation:
the two chains of prime powers `v ^ k` and `Pᵥ ^ k` have matching membership. -/
lemma intValuationDef_map {v : HeightOneSpectrum R} (hv : v ∉ S) (a : R) :
    (primeOfNotMem K S hv).intValuationDef (algebraMap R (S.integer K) a) =
      v.intValuationDef a := by
  rcases eq_or_ne a 0 with rfl | ha
  · simp
  have hfa : algebraMap R (S.integer K) a ≠ 0 := fun h ↦ ha
    (FaithfulSMul.algebraMap_injective R (S.integer K)
      (h.trans (map_zero (algebraMap R (S.integer K))).symm))
  have hmem (k : ℕ) : a ∈ v.asIdeal ^ k ↔
      algebraMap R (S.integer K) a ∈ (primeOfNotMem K S hv).asIdeal ^ k := by
    rw [primeOfNotMem_asIdeal, ← Ideal.map_pow, ← Ideal.mem_comap, comap_map_pow K S hv]
  suffices h : Associates.count (Associates.mk (primeOfNotMem K S hv).asIdeal)
        (Associates.mk (Ideal.span {algebraMap R (S.integer K) a})).factors =
      Associates.count (Associates.mk v.asIdeal) (Associates.mk (Ideal.span {a})).factors by
    rw [v.intValuationDef_if_neg ha, (primeOfNotMem K S hv).intValuationDef_if_neg hfa, h]
  refine Nat.le_antisymm ?_ ?_
  · exact (v.le_count_iff ha _).mpr
      ((hmem _).mpr (((primeOfNotMem K S hv).le_count_iff hfa _).mp le_rfl))
  · exact ((primeOfNotMem K S hv).le_count_iff hfa _).mpr
      ((hmem _).mp ((v.le_count_iff ha _).mp le_rfl))

/-- The valuation of `𝒪_S` at the prime above `v` is the valuation of `R` at `v`. -/
lemma valuation_heightOneSpectrumEquiv (v : {v : HeightOneSpectrum R // v ∉ S}) (x : K) :
    (heightOneSpectrumEquiv K S v).valuation K x = (v : HeightOneSpectrum R).valuation K x := by
  have hR (a : R) : (heightOneSpectrumEquiv K S v).valuation K (algebraMap R K a) =
      (v : HeightOneSpectrum R).valuation K (algebraMap R K a) := by
    have e1 : (heightOneSpectrumEquiv K S v).valuation K (algebraMap R K a) =
        (primeOfNotMem K S v.property).intValuationDef (algebraMap R (S.integer K) a) := by
      rw [IsScalarTower.algebraMap_apply R (S.integer K) K a,
        HeightOneSpectrum.valuation_of_algebraMap]; rfl
    rw [e1, intValuationDef_map K S v.property a, HeightOneSpectrum.valuation_of_algebraMap]; rfl
  obtain ⟨a, b, -, rfl⟩ := IsFractionRing.div_surjective (A := R) x
  rw [map_div₀, map_div₀, hR a, hR b]

/-!
### The class group
-/

/-- `𝒪_S` is torsion-free over `R`, as `R` embeds into it. -/
instance : Module.IsTorsionFree R (S.integer K) := by
  rw [Module.isTorsionFree_iff_algebraMap_injective]
  exact FaithfulSMul.algebraMap_injective R (S.integer K)

/-- Extension of ideals `Cl(R) → Cl(𝒪_S)` is surjective: every ideal of `𝒪_S` is extended from
`R` (`map_comap_eq`). -/
lemma extendedHom_surjective :
    Function.Surjective (ClassGroup.extendedHom R (S.integer K)) := by
  intro c
  obtain ⟨I, rfl⟩ := ClassGroup.mk0_surjective c
  have hI : (I : Ideal (S.integer K)) ≠ ⊥ := by
    have := I.2; rwa [mem_nonZeroDivisors_iff_ne_zero] at this
  refine ⟨ClassGroup.mk0 ⟨(I : Ideal (S.integer K)).comap (algebraMap R (S.integer K)),
    mem_nonZeroDivisors_iff_ne_zero.mpr (comap_ne_bot K S hI)⟩, ?_⟩
  rw [ClassGroup.extendedHom_mk0]
  exact congrArg _ (Subtype.ext (map_comap_eq K S _))

/-- The class group of `𝒪_S` is finite as soon as that of `R` is, being a quotient of it. -/
instance finite_classGroup [Finite (ClassGroup R)] : Finite (ClassGroup (S.integer K)) :=
  .of_surjective _ (extendedHom_surjective K S)

/-- Divisibility by prime powers transfers along extension to `𝒪_S` and back, for primes off
`S` (`comap_map_pow` for the reverse direction). -/
lemma map_le_map_pow_iff {v : HeightOneSpectrum R} (hv : v ∉ S) (J : Ideal R) (k : ℕ) :
    Ideal.map (algebraMap R (S.integer K)) J ≤ (primeOfNotMem K S hv).asIdeal ^ k ↔
      J ≤ v.asIdeal ^ k := by
  rw [primeOfNotMem_asIdeal, ← Ideal.map_pow]
  exact ⟨fun h ↦ Ideal.le_comap_map.trans ((Ideal.comap_mono h).trans (comap_map_pow K S hv k).le),
    Ideal.map_mono⟩

/-- The multiplicity of the extension of an ideal at the prime above `v ∉ S` is the multiplicity
at `v`. -/
lemma count_map_coeIdeal {v : HeightOneSpectrum R} (hv : v ∉ S) {J : Ideal R} (hJ : J ≠ ⊥) :
    count K (primeOfNotMem K S hv)
        ((Ideal.map (algebraMap R (S.integer K)) J : Ideal (S.integer K)) :
          FractionalIdeal (S.integer K)⁰ K) =
      count K v (J : FractionalIdeal R⁰ K) := by
  have hmJ := Ideal.map_ne_bot_of_ne_bot (S := S.integer K) hJ
  rw [count_coe K _ hmJ, count_coe K v hJ, Nat.cast_inj]
  refine Nat.le_antisymm
    ((v.le_count_iff_le hJ _).mpr ((map_le_map_pow_iff K S hv J _).mp
      (((primeOfNotMem K S hv).le_count_iff_le hmJ _).mp le_rfl)))
    (((primeOfNotMem K S hv).le_count_iff_le hmJ _).mpr ((map_le_map_pow_iff K S hv J _).mpr
      ((v.le_count_iff_le hJ _).mp le_rfl)))

/-- The multiplicity of a principal fractional ideal at the prime above `v ∉ S` is the
multiplicity at `v`, by the compatibility of valuations. -/
lemma count_spanSingleton_primeOfNotMem {v : HeightOneSpectrum R} (hv : v ∉ S) (x : Kˣ) :
    count K (primeOfNotMem K S hv) (spanSingleton (S.integer K)⁰ (x : K)) =
      count K v (spanSingleton R⁰ (x : K)) := by
  refine neg_injective (WithZero.exp_injective ?_)
  rw [← valuation_eq_exp_neg_count _ x.ne_zero, ← valuation_eq_exp_neg_count v x.ne_zero]
  exact valuation_heightOneSpectrumEquiv K S ⟨v, hv⟩ (x : K)

/-- The classes of primes in `S` lie in the kernel of extension: such primes extend to `⊤`. -/
lemma closure_le_ker_extendedHom :
    Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) ≤
      (ClassGroup.extendedHom R (S.integer K)).ker := by
  rw [Subgroup.closure_le]
  rintro _ ⟨v, hv, rfl⟩
  rw [SetLike.mem_coe, MonoidHom.mem_ker, HeightOneSpectrum.classGroupMk,
    ClassGroup.extendedHom_mk0]
  refine (ClassGroup.mk0_eq_one_iff _).mpr ?_
  show (Ideal.map (algebraMap R (S.integer K)) v.asIdeal).IsPrincipal
  rw [map_asIdeal_eq_top K S hv]
  exact ⟨1, by simp⟩

/-- The kernel of extension of ideal classes to `𝒪_S` is contained in the subgroup generated by
the classes of the primes in `S`: if `map J = (x)` is principal, then `J` and the principal
fractional ideal `(x)` of `R` have the same valuations off `S` (`count_map_coeIdeal`,
`count_spanSingleton_primeOfNotMem`), so the class of `J` is a product of classes of primes in
`S` (`FractionalIdeal.mk0_mem_closure_of_count_eq`). -/
lemma ker_extendedHom_le :
    (ClassGroup.extendedHom R (S.integer K)).ker ≤
      Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) := by
  intro c hc
  obtain ⟨J, rfl⟩ := ClassGroup.mk0_surjective c
  rw [MonoidHom.mem_ker, ClassGroup.extendedHom_mk0, ← ClassGroup.mk_mk0 K,
    ClassGroup.mk_eq_one_iff_exists] at hc
  obtain ⟨x, hx⟩ := hc
  -- the generator found: `(x) = map J` over `𝒪_S`
  have hxval : spanSingleton (S.integer K)⁰ (x : K) =
      ((Ideal.map (algebraMap R (S.integer K)) (J : Ideal R) : Ideal (S.integer K)) :
        FractionalIdeal (S.integer K)⁰ K) := by
    have h := congrArg Units.val hx
    rwa [coe_toPrincipalIdeal, FractionalIdeal.coe_mk0] at h
  refine FractionalIdeal.mk0_mem_closure_of_count_eq (x := x) fun v hv ↦ ?_
  rw [← count_map_coeIdeal K S hv (mem_nonZeroDivisors_iff_ne_zero.mp J.2), ← hxval,
    count_spanSingleton_primeOfNotMem K S hv x]

/-- The kernel of extension is generated by the classes of the primes in `S`. -/
lemma ker_extendedHom :
    (ClassGroup.extendedHom R (S.integer K)).ker =
      Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) :=
  le_antisymm (ker_extendedHom_le K S) (closure_le_ker_extendedHom K S)

/-- The class group of `𝒪_S` is the class group of `R` modulo the classes of the primes in `S`:
the first isomorphism theorem applied to extension of ideals. -/
noncomputable def classGroupEquiv :
    ClassGroup (S.integer K) ≃*
      ClassGroup R ⧸ Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) :=
  (QuotientGroup.quotientKerEquivOfSurjective _ (extendedHom_surjective K S)).symm.trans
    (QuotientGroup.quotientMulEquivOfEq (ker_extendedHom K S))

end IsDedekindDomain.SInteger
